
version: '3'
volumes:
  phx-chat-postgres-data:
services:
  phx-chat-postgres:
    image: 'postgres:9.5.18'
    volumes:
      - 'phx-chat-postgres-data:/var/lib/postgresql/data' 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
